### ISSUE TITLE
Installation Step

### ISSUE THREAD

**Issue by uwascan** [lucho2d7/openshift-quickstart-laravel5.2#2]
Hello,
This quickstart id looking good but more information about how to install it along with the cartridges mentioned in the readme would be appreciated.

**Comment by ammarfrahm** [comment]
as described on Readme files, [Manual Installation Section](https://github.com/lucho2d7/openshift-quickstart-laravel5.2#manual-installation), you should use The OpenShift Client tools (rhc) to install this cartridge manually.

more about rhc : [developers.openshift.com/managing-your-applications/client-tools.html](https://developers.openshift.com/managing-your-applications/client-tools.html)

**Comment by Noarge** [comment]
Hi there,
I think I followed the steps. But I got this message "ERROR: Please use the https://github.com/boekkooi/openshift-cartridge-php" 
How can I do that if my app is not created yet?

**Comment by mohau-r** [comment]
Hello,
Have you managed to get the manual installation working on your side @Noarge.

Got the same Error.

**Comment by lucho2d7** [comment]
rhc app-create <_app_name_> --env OPENSHIFT_PHP_VERSION=5.6.16 http://cartreflect-claytondev.rhcloud.com/github/boekkooi/openshift-cartridge-nginx http://cartreflect-claytondev.rhcloud.com/github/boekkooi/openshift-cartridge-php mysql-5.5 --from-code=https://github.com/lucho2d7/openshift-quickstart-laravel5.2
