### ISSUE TITLE
No supported encrypter found. The cipher and / or key length are invalid.

### ISSUE THREAD

**Issue by darknblack** [lucho2d7/openshift-quickstart-laravel5.2#3]
RuntimeException in compiled.php line 7477:
No supported encrypter found. The cipher and / or key length are invalid.

After running php artisan make:auth and visiting login/register page

**Comment by unrelaxby** [comment]
Set APP_KEY in config/app.php

**Comment by CodeMuz** [comment]
After the build if you want to make the generated APP_KEY valid and accessible through environment variables then I've resolved some issues on this [pull request](https://github.com/lucho2d7/openshift-quickstart-laravel5.2/pull/4).
